stages:
  - build

build:
  stage: build
  image: electronuserland/builder:wine
  before_script:
    - npm i -g ts ts-node typescript
    - npm install
  script:
    - npm run package:win
  artifacts:
    paths:
      - release/build
