stages:
  - test
  - build

run_tests:
  stage: test
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run test

build:
  stage: build
  image: node:latest
  before_script:
    - npm i -g ts ts-node typescript
    - npm install
  script:
    - npm run package:win
  artifacts:
    paths:
      - release/build
